server:
  port: '8081'
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: 'true'
          batch_size: '50'
    show-sql: 'true'
    hibernate:
      ddl-auto: create
  datasource:
    driverClassName: org.postgresql.Driver
    password: root
    username: postgres
    url: jdbc:postgresql://dbpostgresql:5432/poc_jpa
  main:
    lazy-initialization: 'true'
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    throw-exception-if-no-handler-found: 'true'
  resources:
    add-mappings: 'false'
cors:
  allowed:
    origins: '*'
application:
  description: '@project.description@'
  name: '@project.artifactId@'
build:
  timestamp: '@maven.build.timestamp@'
  version: '@project.version@'
modules:
  logging:
    logs:
      folder:
        path: ./logs
    application:
      name: '@project.artifactId@'
logging:
  level:
    org:
      hibernate:
        type: TRACE
        SQL: DEBUG
